services:
  postgres:
    image: postgres:alpine3.19
    container_name: cortex_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cortex_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    container_name: cortex_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
  cortex_exercises: 