[project]
name = "initialize"
version = "0.1.0"
description = "Initialize Cortex data in the database"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
    "rich>=13.9.1",
    "ruff>=0.6.8",
]
